### PR TITLE
Hidden touch joystick

### PR DESCRIPTION
**Pull request by chuglydude**
Here is the joystick sorry guys

### CODE REVIEW

**Comment by Continuities** [comment]
This is Java code. I'm afraid you may not be ready to contribute to this project.

**Comment by chuglydude** [comment]
Blake told me to do it in JavaScript

**Comment by Continuities** [comment]
Java and javascript are, confusingly, not the same thing.

**Comment by chuglydude** [comment]
oh sorry wrong code its suppose to be java sorry thought you said java script

**Comment by chuglydude** [comment]
i will fix this know

**Comment by Continuities** [comment]
It is supposed to be Javascript. A large portion of the code you submitted
was Java.

**Comment by chuglydude** [comment]
i fixed it and pulled requested it

**Comment by skj3gg** [comment]
I don't see a new pull request. 

Ethan, as @Continuities said earlier, I don't think now is the right time for you to be making coding contributions to this project. You seem to be missing some fundamental principles of programming, git and this project. I encourage you to use one of the many online resources out there to learn the basics of JavaScript, jQuery, git, and Github before attempting another contribution of code.

After you have done this, I will look forward to pull requests from you.

**Comment by chuglydude** [comment]
So sorry I am I know how to code just I make stupid mistakes sometimes I am not perfect I am sorry

I will help code with other people problems 

Ok 

Sorry hope you accept 
This

Ethan

**Comment by Continuities** [comment]
It's okay, man. We appreciate your effort.
Keep on coding!

**Comment by skj3gg** [comment]
> I am not perfect

I promise you, no one is, we are all learning.

Cheers!

**Comment by chuglydude** [comment]
No problem

**Comment by chuglydude** [comment]
(: you guys are awesome

**Pull request closed without merging**
