### PR TITLE
Space Touch Joystick Controls

### PR DESCRIPTION
**Pull request by chuglydude**
Did so many test on them

### CODE REVIEW

**Comment by chuglydude** [comment]
Is the pull request good

**Comment by chuglydude** [comment]
Code good

**Comment by skj3gg** [comment]
Please be patient as we review the code.

**Comment by chuglydude** [comment]
No problem take your time I will be here 24/7

**Comment by chuglydude** [comment]
OMG I JUST PLAYED IT ON MY IPHONE IT WORKS SO WELL YESS

**Comment by chuglydude** [comment]
Nothing has bugs with this feature (:

**Comment by skj3gg** [comment]
I'm trying on my phone and it's not working. I put your branch on my fork and placed it as my gh-pages. http://grotewold.me/adarkroom








Not seeing controls and not responding to touches.

**Comment by chuglydude** [comment]
This is the link to go to 
http://adarkroom.doublespeakgames.com/index.html?ignorebrowser=true

And click play anyways

Ok

**Comment by skj3gg** [comment]
If you think you have it working an you capture a screen shot or tell me how to replicate your experience

**Comment by chuglydude** [comment]
What phone do you have?

**Comment by chuglydude** [comment]
Alright send you a video

**Comment by skj3gg** [comment]
That site doesn't have your changes yet so how could you  know theyre working? This was about the ship touch controls.
Too late for me right now, I'll talk about this in the morning.

**Comment by skj3gg** [comment]
This game doesn't use canvas elements, so I don't know why it is referencing them, the ship does not shot rockets or bullets so that code is unnecessary as well. I don't think this code [was meant for A Dark Room](http://www.codeproject.com/Articles/594186/Create-a-Cross-browser-Touch-based-Joystick-with-H) and does not connect into the game at all, as there isn't even a reference to it in any location, like `index.html`, `space.js` and `ship.js`.

Sadly, I must decline this pull request as it is not a fully thought out implementation and does not solve the problem it set out to accomplish, not to mention a direct copy of someone else's code (minus some comments) with no attribution to them. Thank you for your effort @chuglydude, I appreciate the try but I don't think this was properly tested to see if it worked. Everything up the ship worked before this PR, as seen when playing http://adarkroom.doublespeakgames.com from a mobile device, but the ship still fails because your changes aren't committed to the public website yet, and when I tried from http://skj3gg.github.io/adarkroom (my instance that has your changes) the ship continued to not work.

**Comment by chuglydude** [comment]
I am very sorry i tried

**Comment by chuglydude** [comment]
I found the right code I will test it to see ok

**Comment by skj3gg** [comment]
I don't think just finding code and throwing it into this project is going to create this feature. This code will probably require a (hopefully small) library and some hand-crafted code specific to ADR. Tutorials can give you a general idea of how to create this, but don't really provide the code needed for this specific system.

**Pull request closed without merging**
