### PR TITLE
Add ability to scroll village / storesContainer via keyboard

### PR DESCRIPTION
**Pull request by anubisthejackle**
References Issue #115 

When on Outside tab, if village / storesContainer expand beyond the viewport, this PR allows you to use your keyboard's up and down keys to scroll the sidebar.

Future enhancement could be integrating with the mousewheel.

### CODE REVIEW

**Comment by skj3gg** [comment]
This is a good start, opens the question on scrolling, when pushing down I expect the bar to go up. Does the current way feel natural to others? This doesn't solve the overflow on the starting page of A Dusty Path either. But like I said a great start!

**Comment by anubisthejackle** [comment]
Wasn't seeing the overflow on Dusty path. I'm guessing it has to do with a full store and full perks?

**Comment by skj3gg** [comment]
screen shot 2015-02-07 at 1 34 18 pm

While you actually can see everything, I dont think I have all perks on this save and its clipped the bottom.

**Comment by anubisthejackle** [comment]
Should be a relatively simple process, but it does cause me to rethink the placement of the movement functions. 

I feel they're better put now in Engine (referencing the inView and scrollByX functions)

**Comment by skj3gg** [comment]
+1

**Pull request merged**
