### PR TITLE
Remove ^M from file because to heck with them.

### PR DESCRIPTION
**Pull request by anubisthejackle**
Just as it says, state_manager.js was flooded with ^M, so I removed them.

### CODE REVIEW

**Comment by skj3gg** [comment]
Not sure why the merge is there, but don't think it will do anything once squashed. (Excited to see that PR)

I agree with this, my fear is that this will continue to happen, as changes are made here and there. I'll (or you can) do a little research and see if we can't configure the repository to make commits conform to unix line endings.

Give me a bit to commit.

**Comment by skj3gg** [comment]
committed, Thanks!

**Comment by anubisthejackle** [comment]
Merge was there because I'm working on that issue and didn't have it ready to commit just yet lol Should be done tonight (few minutes?)

**Comment by anubisthejackle** [comment]
@skj3gg https://help.github.com/articles/dealing-with-line-endings/

**Comment by skj3gg** [comment]
Don't know how i missed the .gitattributes section. Thanks!

**Pull request closed without merging**
