### PR TITLE
Adding norwegian as available language

### PR DESCRIPTION
**Pull request by jangerhard**
Let me know if anything needs to be changed, or if I did something wrong.

### CODE REVIEW

**Comment by jangerhard** [comment]
The language list looks a little weird, but this is addressed in #182 and #167

**Comment by skj3gg** [comment]
This PR needs the .js file created from the .po file. There are instructions on how to do this at https://github.com/Continuities/adarkroom/blob/master/doc/translation.txt#L48-L57

Thanks!

**Comment by jangerhard** [comment]
Done!

**Comment by skj3gg** [comment]
Your changes have been merged and are live on https://Continuities.github.io/adarkroom

mange takk!

**Comment by jangerhard** [comment]
It doens't seem to show up when I tried to test it! Could you give it a try?

**Comment by Continuities** [comment]
Haven't had a chance to push it to the live site yet. Will try to remember
tonight!

**Comment by jangerhard** [comment]
Great! 
On Wed, Feb 04, 2015 at 3:08 PM, Michael Townsend <notifications@github.com> wrote:Haven't had a chance to push it to the live site yet. Will try to remember
tonight!

**Pull request closed without merging**
