### PR TITLE
UX Improvement - prevent negative HP

### PR DESCRIPTION
**Pull request by Alex005**
Solution to issue #201

### CODE REVIEW

**Comment by R3van** [comment]
Hey, here goes the tentative first post!

I was looking at this myself, fix looks good once you've included the other attack.

One thing I would say is it might be nicer to prevent the HP value (enemyHp) from falling below 0 by setting it to 0 when the damage exceeds the remaining HP, rather than changing the value of the damage itself? I still want to see how much I got my arse kicked! =P

You can do this in one line (per attack), not sure what the convention is on GitHub for posting code, so if you want me to post it I can.

If no-one's fussed, then feel free to ignore me! =)

**Comment by chuglydude** [comment]
I will fix that after i fix the joystick

**Comment by skj3gg** [comment]
@R3van 
1. Welcome to Open Source!
1. I agree, It is probably best to keep the total damage
1. Feel free to post snippets (<6 line) in between these  \`\`\` and anything bigger I'd put in a [gist](https://gist.github.com/)

**Comment by skj3gg** [comment]
@chuglydude
This is already being taken care of.

**Comment by chuglydude** [comment]
ok no problem

**Comment by R3van** [comment]
@skj3gg 

Thanks! =)

In the attack functions, I'd replace:

```enemyHp -= dmg;```

with:

```enemyHp = enemyHp - dmg <= 0 ? 0 : enemyHp - dmg;```

**Comment by skj3gg** [comment]
Merged in [5d12670979](https://github.com/Continuities/adarkroom/commit/5d1267097906623fbf34df4420bcf82e8121a70b)

Thanks for your contribution!

**Pull request closed without merging**
