### PR TITLE
Remove remote services

### PR DESCRIPTION
**Pull request by f297260**
All trackers and remote/duplicate services/libraries removed.

### CODE REVIEW

**Comment by f297260** [comment]
Even if you keep this code in main repository, you won't get data from offline users. I see no reason to include code with custom trackers in main repo. 

Dropbox functionality disabled by default right now (isn't?), but user have to ping dropbox.com servers for some reason.

PS. I'm not asking everyone to stop tracking at their sites - this is right of the host.

**Comment by skj3gg** [comment]
> Even if you keep this code in main repository you won't get data from offline users. 




True but it doesn't hurt them either.




> Users have to ping dropbox.com servers




If I remember correctly, that closure gets returned if the Dropbox config if set to false so should be no pinging.




This repository IS production. If we start changing this and have to maintain two separate branches. One that has nessesary production things like the tracker, and one that doesn't, it will become quite a bit harder to do deployments. 




I'm sorry but I disagree with this request

**Comment by f297260** [comment]
> If I remember correctly, that closure gets returned if the Dropbox config if set to false so should be no pinging

Somewhat correct, but user browser will request content from dropbox.com servers regardless of setting in config file, see line 20
`<script src="https://www.dropbox.com/static/api/dropbox-datastores-1.1-latest.js" type="text/javascript"></script>`
and will wait for timeout (since it's in offline mode).

> This repository IS production.

Okay then there should be warning about pieces in code you may want to modify.

> True but it doesn't hurt them either.

There is difference. They will experience lag during first load due to requests to unreachable hosts (google.com, dropbox.com). You may laugh at me, but there difference between nothing (3 ms load from hdd/ram cache)  and something 350-1000ms page load with several timeouted requests. Thats why I suggesting this change. This is not only from standpoint of privacy / user tracking.

As compromise, I suggest to include code that will load code affected by my changeset but only after user agrees to prompt *"send stats about my gameplay to the official adarkroom server/tracker"*.

Since this game pretends to be free (mozilla v2 license), I expect some predictable behavior regarding user data. While it's may be absolutely fine to collect data to improve game and give feedback to developers (and it may indeed have positive results), I find it's questionable *to collect data without user permission for this*.

**Comment by Continuities** [comment]
All that aide, you've also taken out jQuery, without which ADR will not function.

**Comment by Continuities** [comment]
Aside*

**Comment by f297260** [comment]
> All that aide, you've also taken out jQuery, without which ADR will not function.

Except it will, there 2 jQuery versions, local and remote:
https://github.com/f297260/adarkroom/commit/ae931c59fa310b27d2264be56de48e2e61002ece#diff-eacf331f0ffc35d4b482f1d15a887d3bL19
https://github.com/f297260/adarkroom/commit/ae931c59fa310b27d2264be56de48e2e61002ece#diff-eacf331f0ffc35d4b482f1d15a887d3bL23

**Pull request closed without merging**
