### PR TITLE
Adding norwegian as available language

### PR DESCRIPTION
**Pull request by jangerhard**
Adding norwegian as available language. 

Will create translation soon!

### CODE REVIEW

**Comment by Continuities** [comment]
Let's wait until the translation is competed to add it to the menu. Thanks:

**Comment by jangerhard** [comment]
Alright, great! I'm new to this though, so how should I go forward with uploading the files? 
On Sun, Feb 01, 2015 at 8:12 PM, Michael Townsend <notifications@github.com> wrote:Let's wait until the translation is competed to add it to the menu. Thanks:

**Comment by Continuities** [comment]
Do all the work in your fork, then submit a pull request once everything's
done.

**Comment by skj3gg** [comment]
I assume this will be Bokmål, in which case, name your folder `nb` please. If Nynorsk, `nn`.

Been wait for this translation! Not fluent enough myself to translate. Takk!

**Comment by jangerhard** [comment]
Yeah, it'll be bokmål! I could do it in nynorsk too, but I'll leave it at bokmål first. This'll be my first contribution to a github project! 
On Sun, Feb 01, 2015 at 8:26 PM, Blake Grotewold <notifications@github.com> wrote:I assume this will be Bokmål, in which case, name your folder nb please. If Nynorsk, nn.

Been wait for this translation! Not fluent enough myself to translate. Takk!

**Pull request closed without merging**
