### PR TITLE
Hidden touch joystick

### PR DESCRIPTION
**Pull request by chuglydude**

### CODE REVIEW

**Comment by Continuities** [comment]
That looks like the beginning of a touch interface, but it's not ready for a pull request yet. It needs to be integrated into the game and be fully functional.

**Comment by chuglydude** [comment]
How do integrate it in the game?

**Comment by skj3gg** [comment]
How does this touch interface control the game? Where is the code that say if "you are touching here, the ship goes there"?

Answer these and it will be integrated.

**Comment by chuglydude** [comment]
Let me resend the code because it is not in js its in c


Is that ok?
From,
Ethan



Sent from my Samsung Galaxy Tab®4


-------- Original message --------

**Comment by chuglydude** [comment]
I found it in Java I will redo it so it will make you happy you will like it.
From,
Ethan

**Comment by skj3gg** [comment]
Before you send any code, test to see that it works in the game.

**Comment by chuglydude** [comment]
Ok no problem

**Pull request closed without merging**
