### PR TITLE
Add convention pieces. jshintrc and gitattributes

### PR DESCRIPTION
**Pull request by skj3gg**
Wanted to get opinions on the `.gitattributes`. (cc @anubisthejackle, @rgravina, @Continuities)

### CODE REVIEW

**Comment by anubisthejackle** [comment]
Looks good to me. Since I do 99% of my dev on Linux, the CRLF has been a constant annoyance.

**Comment by Continuities** [comment]
I'm pretty new to git, so I had to read up on `.gitattributes`. Looks like `* text=auto` should be sufficient to normalize line endings to LF. Do we really need the more specific rules afterwards?

**Comment by skj3gg** [comment]
You're probably right that it would, didn't hurt to be explicit, but as far as I know, should still normalize them down to LF

**Comment by anubisthejackle** [comment]
Could remove and re-add if they don't fix.

Travis Weston

tweston@bangordailynews.com
Phone: 207-990-8206

*Product Developer*
*Research & Innovation Department*
*Bangor Daily News <http://bangordailynews.com/>*

**Comment by Continuities** [comment]
So long as git properly identifies those files as text, which I think it should...

**Pull request merged**
